services:
  - type: web
    name: surgery-app
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y wkhtmltopdf && \
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000 --server.address 0.0.0.0
